import { poppins } from '../../public/fonts';

import type { Metadata } from 'next';

import './globals.css';



export const metadata: Metadata = {
  title: 'Hemanth Babu S | Portfolio',
  metadataBase: new URL('https://hemanthbabu648.com'),
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
